repos:
  # Python formatting (backend only)
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          [
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --expand-star-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
            --recursive,
            --in-place,
            --exclude=__init__.py,
          ]
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: \.py$

  # Frontend formatting (TypeScript/JavaScript)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|jsx|json|css|scss|md)$
        exclude: ^(backend/|tests/|config/|docs/)
        args: ["--write"]

  # General file hygiene (separate for Python and Frontend)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.py$
        exclude: ^frontend/
      - id: end-of-file-fixer
        files: \.py$
        exclude: ^frontend/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        files: \.(json)$
      - id: check-toml
        files: \.(toml)$

  # Frontend-specific file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|md)$
      - id: end-of-file-fixer
        files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|md)$
