repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: \.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: [--fix]
        files: \.py$
      - id: ruff-format
        files: \.py$

  # Frontend formatting (TypeScript/JavaScript)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|jsx|json|css|scss|md)$
        exclude: ^(backend/|tests/|config/|docs/)
        args: ["--write"]

  # General file hygiene (separate for Python and Frontend)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: \.py$
        exclude: ^frontend/
      - id: end-of-file-fixer
        files: \.py$
        exclude: ^frontend/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
        files: \.(json)$
        exclude: tsconfig.*\.json$
      - id: check-toml
        files: \.(toml)$

  # Frontend-specific file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|md)$
      - id: end-of-file-fixer
        files: ^frontend/.*\.(ts|tsx|js|jsx|css|scss|md)$
